### PR TITLE
Add tests to CI

### PR DESCRIPTION
**Pull request by francescofarina**
## Proposed changes

Change to run tests for PRs #64.

### CODE REVIEW

**Comment by francescofarina** [comment]
Using this to test the workflow

**Comment by francescofarina** [comment]
For some reasons some operations performed in the tests break the CI, e.g. line 56 of `collate.py`.

**Comment by TristanBilot** [comment]
We can really run tests on `macos-14`? 😳

**Comment by francescofarina** [comment]
Yes ;) See [here](https://github.blog/changelog/2024-01-30-github-actions-macos-14-sonoma-is-now-available/).

Everything is installed correctly including mlx but some tests seem to break the process. I know `test_batch` and `test_message_passing` cause the process to break but testing the utils seems to work fine.
I can't reproduce it locally so it may as well be an issue with the new runners.

**Comment by TristanBilot** [comment]
hmm, so what do you recommend to do?

**Comment by francescofarina** [comment]
Let me explore it more and also let's wait a few days as macOS runners have just been released and there may be issues to be fixed.

**Comment by francescofarina** [comment]
Still no luck with this - and it's hard to debug as it can't be reproduced locally. I suggest we leave this open as a draft and go back to it in a few days. Meanwhile let's be diligent with local testing.

**Pull request closed without merging**
